name: user_repository
description: Dart package which manages the user domain.
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  servicestack: ^2.0.2
  equatable: ^2.0.0
  uuid: ^3.0.0
